### PR TITLE
Create hello rails

### PR DESCRIPTION
**Pull request by didierganthier**
## Checklist
- [x] I have read this repository's contribution guidelines.
- [x] My pull request has a descriptive title (not a vague title like Update index.MD)
- [x] My pull request targets the main branch of this [project](https://github.com/didierganthier/hello-rails-react).
- [x] I added relevant documentation for all the files I changed

## Summary
This PR creates the `hello-rails-react` app

 ## What changes have been made?
- [x] Create a new Rails app called 'hello-rails-react'.
     - Use the command `rails new -j webpack my_new_rails_app` as described in the previous lesson's tutorial.
 - [x] Verify that the `jsbundling-rails` gem is added to your Gemfile.
 - [x] Initialize your project with Git.
 - [x] Install needed node dependencies as described in the previous lesson's tutorial.
 - [x] Create a `babel.config.js` in the root folder of your project as described in the previous lesson's tutorial.
 - [x] Update `webpack.config.js` to include the babel loader as described in the previous lesson's tutorial.
 - [x] Make sure that your project has a Postgres database set up. 
 - [x] Create a table for storing your messages and create 5 different greetings. 
 - [x] Create an API endpoint that selects a random greeting from your table (you will need a controller with an action and Rails route).
 - [x] Create a static view that will be the root of your app.
- [x] Create the `App` component with react-router and render it in your static view.
- [x] Create the `Greeting` component that will display a greeting. Set it up as a route in your App component.
- [x] Create a store, an action, and a reducer that will connect to your API endpoint to get the random greeting.
- [x] Display the random greeting in your `Greeting` component.

## Author
- @didierganthier

### CODE REVIEW

**Review by cynthiainga — COMMENTED** [review]
Hi @didierganthier, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn’t follow Gitflow. The Pull Request should be made from the “feature branch” into the "dev branch", you can use this [documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request) that show how to change the base branch 😉 ✌️ 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by didierganthier** [comment]
Thanks @cynthiainga I changed it 😅

**Review by Whoistolu — APPROVED** [review]
### Hi @didierganthier 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

### Highlight
✔️ `jsbundling-rails` gem was used
✔️ `react-dom`, `babel-loader` dependencies was added
✔️ API endpoint for returning a random greeting was created
✔️ Controller with one action was created
✔️ `App`component has a route that leads to the `Greeting` component

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by didierganthier** [comment]
Thanks @Whoistolu 😉

**Pull request merged**
